name = "mirabilis"
author = "jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "383ede3bc01ad6d3ce5d04e6728c72c841c58b29edb079f163da94113b56a7f7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
