name = "mirabilis"
author = "jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36793ad90def73b3c690d56ab5ad0096e4682668b4895f3c074f1cd370b24317"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
