name = "mirabilis"
author = "jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "152c75b1a48f0d8b4acb9e4faa9ed161da81349261c57cf1ab835bf3fa361253"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
